### ISSUE TITLE
latest package broken

### ISSUE THREAD

**Issue by dweisiger** [PinataCloud/Pinata-SDK#105]
i recently merged a PR into the pinata-sdk, and it published a new version 1.1.24 for npm. however the generated lib files https://github.com/PinataCloud/Pinata-SDK/tree/master/lib were not updated with the changes in the source code. i am not familiar with the build/release process for the sdk, so could someone please take a look at updating these lib files? i also noticed that there is not a new release/tag 1.1.24 on github, even though it has been updated in the package.json and in npm

**Comment by obo20** [comment]
This should be fixed with 1.1.25
