### ISSUE TITLE
Upload files to Piñata from S3

### ISSUE THREAD

**Issue by damianlluch** [PinataCloud/Pinata-SDK#112]
Hi, I'm trying to upload files from S3 to IPFS via Piñata. Through the SDK it has been impossible, so I am trying via AXIOS.
I manage to upload one file, but if I want to upload more than one I get this error:

`More than one file and/or directory was provided for pinning.`

I've seen people with the same problem and I've also seen a solution in Python.

Any suggestions on how to fix this in Node?

thanks

This is my code:

```
try {
      const form = new FormData();
      /** for (const item of items) {
        const file = getObjectStream(item.tokenURI, bucket, path); // return Readable objet
        form.append('file', file, {
          filename: item.tokenURI,
        });
      } **/

      const fileOne = getObjectStream(
        '_1_QDK5CsvMwd-9Q1rjFG.jpeg',
        bucket,
        path,
      );
      form.append('file', fileOne, {
        filename: '_1_QDK5CsvMwd-9Q1rjFG.jpeg',
      });
      const fileTwo = getObjectStream(
        '-OYIR4OQegkpxh4Xnoul8.jpeg',
        bucket,
        path,
      );

      form.append('file', fileTwo, {
        filename: '-OYIR4OQegkpxh4Xnoul8.jpeg',
      });

      console.log(`Uploading files to IPFS`);
      const pinataOptions: PinataOptions = {
        cidVersion: 1,
      };

      const config = {
        method: 'post',
        url: 'https://api.pinata.cloud/pinning/pinFileToIPFS',
        maxBodyLength: Infinity,
        headers: {
          pinata_api_key: 'XXXXXXXXXX',
          pinata_secret_api_key:
            'XXXXXXXXXXXX',
          ...form.getHeaders(),
        },
        data: form,
      };

      // @ts-ignore
      axios(config)
        .then(function (response) {
          console.log(JSON.stringify(response.data));
        })
        .catch(function (error) {
          console.log(error);
        });

      //console.log(`Piñata Response:`, JSON.stringify(result, null, 2));
      //return result.IpfsHash;
    } catch (e) {
      console.error(e);
    }
    ```

**Comment by njculpin** [comment]
hey this worked for me...

`import type { ValidatedEventAPIGatewayProxyEvent } from "@libs/api-gateway";
import { formatJSONResponse } from "@libs/api-gateway";
import { middyfy } from "@libs/lambda";
import schema from "./schema";
const AWS = require("aws-sdk");
const s3 = new AWS.S3();
const { Readable } = require("stream");
const pinataSDK = require("@pinata/sdk");
const pinata = pinataSDK(process.env.PINATA_KEY, process.env.PINATA_SECRET);

const retrieve: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (
  event
) => {
  try {
    let filename = event.body.filename as String;
    var params = {
      Bucket: 'bucket_name',
      Key: filename,
    };
    let dataURL = s3.getObject(params).promise();
    const data = dataURL.replace(/^data:image\/png;base64,/, "");
    const buff = Buffer.from(data, "base64");
    const stream = Readable.from(buff);
    stream.path = filename;
    const res = await pinata.pinFileToIPFS(stream);
    return formatJSONResponse(res);
  } catch (err) {
    return formatJSONResponse(err);
  }
};

export const main = middyfy(retrieve);`

**Comment by njculpin** [comment]
try this...

```
import type { ValidatedEventAPIGatewayProxyEvent } from "@libs/api-gateway";
import { formatJSONResponse } from "@libs/api-gateway";
import { middyfy } from "@libs/lambda";
import schema from "./schema";
const AWS = require("aws-sdk");
const s3 = new AWS.S3();
const axios = require("axios");
const FormData = require("form-data");

const pinFile: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (
  event
) => {
  try {
    let filename = event.body.filename as String;
    var params = {
      Bucket: process.env.BUCKET_NAME,
      Key: filename,
    };
    try {
      await s3.headObject(params).promise();
      console.log("File Found in S3");
    } catch (err) {
      console.log("File not Found ERROR : " + err);
      throw new Error(err);
    }
    let stream = s3.getObject(params).createReadStream();
    var data = new FormData();
    data.append("file", stream, {
      filename: filename,
    });
    data.append("pinataOptions", '{"cidVersion": 1}');
    var config = {
      method: "post",
      url: "https://api.pinata.cloud/pinning/pinFileToIPFS",
      headers: {
        pinata_api_key: process.env.PINATA_KEY,
        pinata_secret_api_key: process.env.PINATA_SECRET,
        ...data.getHeaders(),
      },
      data: data,
    };
    let res = await axios(config);
    let IpfsHash = res.data.IpfsHash;
    console.log("IpfsHash", IpfsHash);
    return formatJSONResponse({ IpfsHash: IpfsHash });
  } catch (err) {
    return formatJSONResponse(err);
  }
};

export const main = middyfy(pinFile);
```

**Comment by damianlluch** [comment]
> Hi, I'm trying to upload files from S3 to IPFS via Piñata. Through the SDK it has been impossible, so I am trying via AXIOS. I manage to upload one file, but if I want to upload more than one I get this error:
> 
> `More than one file and/or directory was provided for pinning.`

Hi, with this code you can upload more than one file to Pinata?

thanks!

**Comment by rommel-pinata** [comment]
Hey, @damianlluch  checked API and for now, this is not supported. However, this functionality is currently being developed and should be available in the next sprint. Once released I will work in the integration if needed.

Duplicated #112 and #115

**Comment by hiren-chestr** [comment]
@rommel-pinata found an issue in SDK, upload successfully works, if we append fileName at a time of appending stream to file object. snippet below.

```
export default function pinFileToIPFS(config, readStream, options) {
    return new Promise((resolve, reject) => {

        const data = new NodeFormData();

        data.append('file', readStream, {
           filename: 'IPFSImage'
        });
```

**Comment by rommel-pinata** [comment]
Hey @hiren-chestr I'm checking on this

**Comment by rommel-pinata** [comment]
Hey @hiren-chestr I added a fix and refactor function pinFileToIPFS

**Comment by hironate** [comment]
Thanks @rommel-pinata for quick fix.
