### ISSUE TITLE
More than one file and/or directory was provided for pinning.

### ISSUE THREAD

**Issue by ferdiunal** [PinataCloud/Pinata-SDK#115]
Hello, when I want to send more than one file with [Http Client](https://laravel.com/docs/9.x/http-client#main-content) or [Guzzle](https://docs.guzzlephp.org/en/stable/) in Laravel, "More than one file and/or directory was provided for pinning." I am getting this response. What would you suggest I do?

```php 
public function client()
{
    return Http::withHeaders([
        'pinata_api_key' => config('services.pinata.key'),
        'pinata_secret_api_key' => config('services.pinata.secret'),
    ])
        ->withUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36")
        ->withToken(config('services.pinata.accessToken'))
        ->baseUrl(
            config('services.pinata.url')
        );
}

public function uploadFiles(array $files = [])
{
    if (count($files) === 0) {
        return [];
    }

    $client = $this->client();
    LazyCollection::make($files)->each(
        fn($file, $key) => $client->attach(
            "file",
            File::get($file),
            basename($file),
            ['mimeType' => 'application/octet-stream']
        )
    );
    
    $response = $client
        ->asMultipart()
        ->connectTimeout(120)
        ->timeout(120)
        ->post('/pinning/pinFileToIPFS');
    return $response->json();
}
```

**Comment by ferdiunal** [comment]
This is how I use it.

```php** 

$pinata = new \App\Library\Pinata;

$pinata->uploadFiles([
  public_path("img/images_small/46.png"),
  public_path("img/images_small/55.png"),
]); 

```

**Comment by bsormagec** [comment]
any update @obo20 ?

**Comment by rommel-pinata** [comment]
Hey, @bsormagec I checked API and for now, this is not supported. However, this functionality is currently being developed and should be available in the next sprint. Once released I will work in the integration if needed.

Duplicated #112 and #115

**Comment by bsormagec** [comment]
How many week your sprint length 😄

**Comment by rommel-pinata** [comment]
@bsormagec Usually takes 2 weeks. As soon as is approved and deployed in production, I'll let you know!

**Comment by rommel-pinata** [comment]
@bsormagec This is now supported. let me know if you are able to upload a folder.

**Comment by devjoaov** [comment]
@rommel-pinata is uploading a folder really supported? I have tried many times with the latest version and I always got an `Error: readStream is not a readable stream or form data`. Could you help me? My code:

```js
import NodeFormData from 'form-data';

let data = new NodeFormData();
data.append("file", JSON.stringify({ name: "testing 1" }), {
  filename: "testing1",
});
data.append("file", JSON.stringify({ name: "testing 2" }), {
  filename: "testing2",
});

const options = {
  pinataMetadata: {
    name: "test_upload_directory",
  },
};

const hash = await pinata
  .pinFileToIPFS(data, options)
  .then((result) => {
    return result.IpfsHash;
  });
```

**Comment by rommel-pinata** [comment]
Hello @devjoaov pinFileToIPFS expects a readable stream. This is an example of a readable stream 

```
const fs = require('fs');
const readableStreamForFile = fs.createReadStream('./yourfile.png');
const options = {
    pinataMetadata: {
        name: MyCustomName,
        keyvalues: {
            customKey: 'customValue',
            customKey2: 'customValue2'
        }
    },
    pinataOptions: {
        cidVersion: 0
    }
};
pinata.pinFileToIPFS(readableStreamForFile, options).then((result) => {
    //handle results here
    console.log(result);
}).catch((err) => {
    //handle error here
    console.log(err);
});
```

However I think you are trying to upload a folder for that I suggest you use pinata.pinFromFS(sourcePath, options) where sourcepath can be a file or a folder

**Comment by devjoaov** [comment]
@rommel-pinata bumping you for this ☝️

**Comment by rommel-pinata** [comment]
Ohh I get your problem now, unfortunately for now we only support files in the storage. I'll add this functionality to the roadmap. It would seem really helpful!.

**Comment by devjoaov** [comment]
Great, @rommel-pinata , thank you for replying
