### ISSUE TITLE
upload folder fialed

### ISSUE THREAD

**Issue by cxqi** [PinataCloud/Pinata-SDK#133]
my program

```
const fs = require('fs');
const path = require('path');
const pinataSDK = require('@pinata/sdk');
const pinata = pinataSDK(API Key,API Secret);
async  function main(){
    const imgPath = path.join(__dirname,'..','img')
    const files = fs.readdirSync(imgPath)
    for(var i = 0;i< files.length;i++){
        console.log('Pinning to pinata ....')
        const readableStreamForFile = fs.createReadStream(imgPath+`/${files[i]}`);
        let result = await pinata.pinFileToIPFS(readableStreamForFile);
        hashes.push(result.IpfsHash);
    }
}

main();
```
I get this error when compiling

TypeError: pinataSDK is not a function
    at Object.<anonymous> (/Users/steven/Documents/Node/src/pin-to-ipfs/scripts/upload.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by Jase-Legi** [comment]
Same

**Comment by rommel-pinata** [comment]
hey @cxqi @Jase-Legi Checking on it, Could you place which version of the SDK you are using?

**Comment by Jase-Legi** [comment]
> hey @cxqi @Jase-Legi Checking on it, Could you place which version of the SDK you are using? as well as any info that may be useful environment, node version etc.

-The latest version. 2.0, however I literally just updated it because I figured it would solve the issue, I had the previous version before but had the same issue

**Comment by polluterofminds** [comment]
While @rommel-pinata looks into this, can you please try downgrading to this version? https://www.npmjs.com/package/@pinata/sdk/v/1.2.1 

`npm i @pinata/sdk@1.2.1`

**Comment by Jase-Legi** [comment]
> While @rommel-pinata looks into this, can you please try downgrading to this version? https://www.npmjs.com/package/@pinata/sdk/v/1.2.1
> 
> `npm i @pinata/sdk@1.2.1`

yeah, I had  already downgraded, thanks.

**Comment by rommel-pinata** [comment]
We released a new version v2.0.0

I created this small example with js and is working well. Let me know if you still experience any issues!
```
const pinataSDK = require('@pinata/sdk');
const keys = require("./key");


const pinata = new pinataSDK(keys.apiKey,keys.apiSecret);

async function exec(){
    const result = await pinata.pinFromFS("/Users/rommelberrios/Documents/pinata/Pinata-SDK/pinata.png", {pinataMetadata: {name: "different-name.jpg"}});
    console.log('result', result)
}

exec()
```

**Comment by cxqi** [comment]
> [rommel-pinata](/rommel-pinata)

* node version v12.18.3
* npm version v6.14.6
* pinata sdk @pinata/sdk@2.0.0-beta.0

**Comment by cxqi** [comment]
hey@rommel-pinata the version of node I use and the sdk of pinata
* node version v12.18.3
* npm version v6.14.6
* pinata sdk @pinata/sdk@2.0.0-beta.0

**Comment by cxqi** [comment]
> > [rommel-pinata](/rommel-pinata)
> 
> * node version v12.18.3
> * npm version v6.14.6
> * pinata sdk @pinata/sdk@2.0.0-beta.0

**Comment by cxqi** [comment]
> While @rommel-pinata looks into this, can you please try downgrading to this version? https://www.npmjs.com/package/@pinata/sdk/v/1.2.1
> 
> `npm i @pinata/sdk@1.2.1`
Thanks a lot, the problem is solved
