### ISSUE TITLE
[ERROR] Error: filename was not provide, make sure to provide options.pinataMetadata.name

### ISSUE THREAD

**Issue by yakovsamsonov** [PinataCloud/Pinata-SDK#140]
version: "2.1.0"

I'm calling pinFileToIPFS in src/pinning/pinFileToIPFS.ts without options variable provided.
This is valid function call based on function signature and README.md.

I've got an Error: filename was not provide, make sure to provide options.pinataMetadata.name.

Looks like the issue with 89-99 lines after refactoring.

**Comment by rommel-pinata** [comment]
Hello, @yakovsamsonov I see the error in the optional parameter. So it seems it's rather an issue on the documentation or has a different interface.

**Comment by stevedylandev** [comment]
We will be rewriting the SDK to make this a non-issue
