### ISSUE TITLE
[ERROR] - Malformed content type

### ISSUE THREAD

**Issue by hironate** [PinataCloud/Pinata-SDK#147]
Suddenly Pinata SDK started giving weird error. **Malformed content type**, anybody knows what's the reason ?
here is snippet.

```const pinataClient = createPinataClient();
    const stream = downloadS3Stream({
      Key: fileUrl
    });


    const result = await pinataClient.pinFileToIPFS(stream);

    return result;
   ```

**Comment by hiren-chestr** [comment]
Seems like the current release is not supporting without options, updated to release v2.0.0, passed options and worked.

**Comment by hironate** [comment]
Seems like the current release is not supporting without options, updated to release v2.0.0, passed options and worked.

**Comment by hironate** [comment]
Tried passing with current released version, it did not work.

**Comment by hironate** [comment]
@aswatyn @rommel-pinata 
yeah, already did work around. how can i contribute to improve doc ?
