### ISSUE TITLE
Can't resolve 'fs' while importing @pinata/sdk in next js

### ISSUE THREAD

**Issue by shravanandoria** [PinataCloud/Pinata-SDK#148]

**Comment by rommel-pinata** [comment]
CUrrently checking this issue.

**Comment by stevedylandev** [comment]
Hey there! This can happen if you are importing to a client side component or page vs a server side component. You can check out a template we have for Next.js here: https://github.com/PinataCloud/pinata-app-router-starter 

We will be rewriting the SDK which should help resolve this in the future
