### ISSUE TITLE
PinataMetadata type is not matching SDK documentation

### ISSUE THREAD

**Issue by Freezystem** [PinataCloud/Pinata-SDK#161]
Hi Pinata Dev Team !  

The [PinataMetadata](https://github.com/PinataCloud/Pinata-SDK/blob/master/types/src/commands/data/pinList/pinList.d.ts#L7-L9) type is not matching the metadata used throughout the SDK documentation.  
See [here](https://docs.pinata.cloud/reference/pinningpinfiletoipfs#pinata-metadata) and [here](https://docs.pinata.cloud/docs/pinata-sdk#hashmetadata) for example.

The correct type would be something like:

```ts
export interface PinataMetadata {
    name?: string;
    keyvalues?: {
        [key: string]: string | number | null;
    }
}
```

I'm willing to make a PR if you want me to. 😇 
Regards,

**Comment by stevedylandev** [comment]
Hey there! Thank you for this feedback, we are currently rewriting the SDK and will keep this in mind!
