### ISSUE TITLE
Need Help: formidable is not working in my NextJs App to

### ISSUE THREAD

**Issue by L1xus** [PinataCloud/Pinata-SDK#170]
Hi!
I'm trying to upload a file to pinata with pinata-sdk following the same structure in the NextJs starter [](https://docs.pinata.cloud/sdks/nextjs-starter) 

client side:
```typescript
const handleCoverImage = async (e) => {
    const file = e.target.files[0]
    const reader = new FileReader()
    reader.onload = () => {
      setFormData(prevState => ({
        ...prevState,
        coverImage: file,
        coverImagePreview: reader.result
      }))
    }
    reader.readAsDataURL(file)
    
    try {
      const fileData = new FormData()
      fileData.append('file', file, file.name)
      const res = await fetch('/api/author', {
        method: 'POST',
        body: fileData,
      })
      const ipfsHash = await res.text()
      console.log('ifpsHash:',ipfsHash)
    } catch (error) {
      console.error('Error Pinning File!', error)
      throw error
    }
  }
``` 
server side:
```typescript
export const pinFile = async (file) => {
  try {
    const readableStreamForFile = fs.createReadStream(file.filepath)
    const options = {
      pinataMetadata: {
        name: file.originalFilename,
      },
    }
    const result = await pinata.pinFileToIPFS(readableStreamForFile, options)
    fs.unlinkSync(file.filepath)
    console.log('shit:', result)
    return result
  } catch (error) {
    console.error('Error Pinning File to IPFS')
    throw error
  }
}

export async function POST(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'POST') {
    try {
      const form = formidable({})
      form.parse(req, async function (err, fields, files) {
        if (err) {
          console.log({ err });
          return res.status(500).send("Pin Error")
        }
        const response = await pinFile(files.file)
        const { IpfsHash } = response

      res.status(200).send('File processed successfully')
      })
    } catch (e) {
      console.log(e)
      res.status(500).send("Server Error")
    }
  }
}
```

these are the errors I get :/
`⨯ Error: No response is returned from route handler '/home/astro/Astro_dev/AstroLib/app/src/app/api/author/route.ts'. Ensure you return a `Response` or a `NextResponse` in all branches of your handler.
    at /home/astro/Astro_dev/AstroLib/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:63974
    at async eU.execute (/home/astro/Astro_dev/AstroLib/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53964)
    at async eU.handle (/home/astro/Astro_dev/AstroLib/app/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:65062)
    at async doRender (/home/astro/Astro_dev/AstroLib/app/node_modules/next/dist/server/base-server.js:1315:42)
    at async cacheEntry.responseCache.get.routeKind (/home/astro/Astro_dev/AstroLib/app/node_modules/next/dist/server/base-server.js:1537:28)
TypeError: req.on is not a function
    at IncomingForm.parse (webpack-internal:///(rsc)/./node_modules/formidable/src/Formidable.js:255:8)
TypeError: req.on is not a function
    at IncomingForm.parse (webpack-internal:///(rsc)/./node_modules/formidable/src/Formidable.js:255:8)
 ⨯ node_modules/formidable/src/Formidable.js (236:0) @ IncomingForm.parse
 ⨯ unhandledRejection: TypeError: req.on is not a function
    at IncomingForm.parse (webpack-internal:///(rsc)/./node_modules/formidable/src/Formidable.js:255:8)
null
 ⨯ node_modules/formidable/src/Formidable.js (236:0) @ IncomingForm.parse
 ⨯ unhandledRejection: TypeError: req.on is not a function
    at IncomingForm.parse (webpack-internal:///(rsc)/./node_modules/formidable/src/Formidable.js:255:8)
null`

I tried to work with formData instead of formidable, but the result isn't getting me a filePath :/
```typescript
export async function POST(req: NextApiRequest, res: NextApiResponse) {
  if (req.method === 'POST') {
    try {
      const formData = await req.formData()
      const file = formData.get('file')

      const response = await pinFile(file)
      const { IpfsHash } = response

      res.status(200).send(IpfsHash)
    } catch (error) {
      console.error('Error processing file', error)
      res.status(500).send('Server Error')
    }
 } else {
    res.status(405).send('Method Not Allowed')
 }
}
``` 
can someone help me solve this please :)

**Comment by stevedylandev** [comment]
Hey there! From the error it looks like it might be due to trying to use Next api responses in an Astro project? You may need to alter the code to follow Astro conventions for api requests, unless they have a Next integration

**Comment by stevedylandev** [comment]
Hey there! If you're using App router I would recommend following this template https://github.com/PinataCloud/pinata-app-router-starter

**Comment by L1xus** [comment]
Thanks a lot @stevedylandev!
this works perfectly fine!
