### ISSUE TITLE
Suggestion to use fdir instead of recursive-fs

### ISSUE THREAD

**Issue by thecodrr** [PinataCloud/Pinata-SDK#19]
Hey, wonderful project here. I recently created **the fastest directory crawler for NodeJS** and wanted to share it with the developer community on GitHub. I couldn't help but notice that you guys are using `recursive-fs` which is much slower than `fdir`.

Would you be interested in migrating to `fdir`?

[Here's my project](/thecodrr/fdir) if you are interested and I'd be happy to help where needed.

**Comment by rommel-pinata** [comment]
Hey @thecodrr I removed this dependency in the latest release and instead used `fs` functions
