### ISSUE TITLE
Incorrect statement on help file page

### ISSUE THREAD

**Issue by tjayrush** [PinataCloud/Pinata-SDK#24]
On this page:

https://pinata.cloud/documentation#UserPinPolicy

After the Postman example, but before the Javascript example, it says, "We also pass in the hash to change the pin policy for, as well as the new pin policy."  The Javascript function has a parameter called `ipfsPinHash` that is not used in the example code.

Suggestion: remove the above sentence and the parameter. They are confusing and not used.

**Comment by obo20** [comment]
Thanks for pointing this out!

It looks like a copy and paste remenant from the hashPinPolicy documentation. 

I've gone ahead and changed this up and the changes are now live.
