### ISSUE TITLE
Mispelling

### ISSUE THREAD

**Issue by tjayrush** [PinataCloud/Pinata-SDK#25]
On this page:

https://pinata.cloud/documentation#PinFileToIPFS

it says, "As an example, let's pretend you're building a service for lawyers and want to tag every IPFS upload with the Layer's ID..."

"Layer's ID" should be "Lawyer's ID."

**Comment by obo20** [comment]
Thanks for pointing this out! i've gone ahead and fixed this and the changes are now live.
