### ISSUE TITLE
Is it possible to upload a directory via the pinata http api?

### ISSUE THREAD

**Issue by olizilla** [PinataCloud/Pinata-SDK#4]
From the api docs it looks like it's only possible to upload single files via the http api? Is that correct? It'd be rad to be able to upload entire directories to pinata, for static website hosting. https://github.com/agentofuser/ipfs-deploy makes it super easy to deploy to pinata but right now it's not as easy as it could be.

The current code is using the pinHash api, and the user has to forward a port on their local router to let pinata connect to a local ipfs node.

Being able to add entire directories would be rad. The ipfs and ipfs-cluster both support this via their http api, so it's possible that pinata already supports this and I am just reading the docs wrong.

**Comment by obo20** [comment]
Currently this isn't a feature. 

We'd had a few different people request this, and I've actually created a few different prototypes for how this would work, but I have yet to find a fool proof method that "just works" in a way that doesn't expose our API to certain kinds of attack vectors.

While I don't have a timeline on release for something like this, I can tell you that it is constantly being looked into.

**Comment by obo20** [comment]
This is now available through our file upload endpoint: https://pinata.cloud/documentation#PinFileToIPFS

This is also available for users via our web interface at: https://pinata.cloud/pinataupload

I'm currently exploring how to make this work correctly with the SDK (there's a few tricky edge cases), so I'll keep this issue open, but I wanted users to be aware that the functionality does exist for users who absolutely need this feature and are okay with not using the SDK.

**Comment by obo20** [comment]
This is now integrated into the SDK as of v1.1.0

**Comment by skyrover7** [comment]
> This is now available through our file upload endpoint: https://pinata.cloud/documentation#PinFileToIPFS
> 
> This is also available for users via our web interface at: https://pinata.cloud/pinataupload
> 
> I'm currently exploring how to make this work correctly with the SDK (there's a few tricky edge cases), so I'll keep this issue open, but I wanted users to be aware that the functionality does exist for users who absolutely need this feature and are okay with not using the SDK.

@obo20 can you specify how to use the file upload endpoint to upload a directory? trying to get some basics down in postman but not having any luck with directories (and how to name directories)

**Comment by asger60** [comment]
i'm also interested in learning how to upload directories, or upload into a specific directory

**Comment by asger60** [comment]
sorry it was right there in the text.
`wrapWithDirectory - Wrap your content inside of a directory when adding to IPFS. This allows users to retrieve content via a filename instead of just a hash. For a more detailed explanation, see this informative blogpost. Valid options are: true or false`

**Comment by skyrover7** [comment]
@asger60 so are you able to upload into a specific directory using `wrapWithDictionary`?

**Comment by asger60** [comment]
I never figured it out. I've reverted to just upload the files through Chrome instead. Would love to know if it's possible through http though.

**Comment by nickjuntilla** [comment]
I don't know why this is closed. The documentation only refers to wrapping 1 file at a time, which is not very useful. How can we wrap multiple files or a whole directory? Can we add multiple files as form data? Could we have some documentation around this?

**Comment by skyrover7** [comment]
@nickjuntilla yea i was confused as to why it was closed as well. ended up not needing the directory functionality right now, but eventually will! seems like @asger60 also found a workaround. 

@obo20 are we missing something?

**Comment by asger60** [comment]
The workaround I found was not really perfect, and i keep coming back to this problem. The ideal solution would be to be able to upload into a specific directory - but i can't figure out if that is possible with pinata

**Comment by nickjuntilla** [comment]
I finally found the JavaScript SDK. I can't believe it's existed for 2 years and wasn't in the main docs. That will probably solve my problems. I'm over here using the web form submit on the backend. Pinata docs could really use some help. They need to have the JavaScript SDK front and center. Also the ability to upload multiple files and wrap them in a directory is still not solved via the form upload method. I understand there are probably some limitations but I'm sure a lot of people could use it.

**Comment by Tsunfire** [comment]
There is a v2 API, but it still only specifies uploading a single file.

**Comment by jgrean81** [comment]
+1, this is basic functionality needed please

**Comment by MonarthS** [comment]
SDK:
- single file: [pinFileToIPFS](https://github.com/PinataCloud/Pinata-SDK#pinfiletoipfs)
- directory: [pinFromFS](https://github.com/PinataCloud/Pinata-SDK#pinfromfs)

API:

for single file & directory, API is same for both: `https://api.pinata.cloud/pinning/pinFileToIPFS`. you just need to append multiple files:

- single file: [pinFileToIPFS](https://docs.pinata.cloud/api-pinning/pin-file#javascript-example-with-axios)
- directory: [pinFileToIPFS](https://docs.pinata.cloud/api-pinning/pin-file#pinning-a-directory-example)
