### ISSUE TITLE
Increasing maxContentLength and maxBodyLength in Axios

### ISSUE THREAD

**Issue by vortextemporum** [PinataCloud/Pinata-SDK#40]
I had been going through lots of trouble with pinFromFS function. Because any folder above 10mb could not be uploaded.

I found out that the problem is because of a limitation from Axios configs. I had to change the variables from -1 to infinity:

```
// maxContentLength: -1,
// maxBodyLength: -1,

maxContentLength: 'Infinity',
maxBodyLength: 'Infinity',
```

If you natively support or provide a configuration on function options, it would be much easier for us users.

Thanks

**Comment by obo20** [comment]
Fixed in v1.1.13

**Comment by obo20** [comment]
@vortextemporum can you verify this now works for you?

**Comment by ateeqrehmani** [comment]
@obo20 facing 'Request body larger than maxBodyLength limit' with "@pinata/sdk": "^1.1.13"
file size is 5Mb.
