### ISSUE TITLE
not compatible with nest.js v7

### ISSUE THREAD

**Issue by uncleGena** [PinataCloud/Pinata-SDK#46]
write 
`const pinataSDK = require('@pinata/sdk');`
and it will throw
`TypeError: Map#toJSON isn't generic`

[reproduction](https://github.com/uncleGena/repro_nestjs_pinata)

**Comment by ochukochris** [comment]
I'm facing the same issue did you find a solution?

**Comment by toffick** [comment]
Did anyone find a solution?

**Comment by ochukochris** [comment]
> Did anyone find a solution?

Nope, I had to comment out the part and move on

**Comment by luckypal** [comment]
Same error.

**Comment by lucashenning** [comment]
same here 
```
[Nest] 10173   - 07/29/2021, 12:50:21 PM   [ExceptionHandler] Map#toJSON isn't generic +73ms
TypeError: Map#toJSON isn't generic
```

**Comment by santicevic** [comment]
Same here

**Comment by Velua** [comment]
Also experiencing this issue.

**Comment by giovannivignone** [comment]
Same here. Does not seem like pinata is compatible with nestJS

**Comment by ti0** [comment]
Does anyone from the team have an update if this will be fixed? I was considering to pay for the pro plan and testing out API access, but if the SDK doesn't work then it doesn't seem like it is a reliable service.

**Comment by obo20** [comment]
Right now we cannot promise any timelines on when nest.js will be supported by our JS SDK. 

It’s on our roadmap, but is constantly being prioritized against our other platform needs.

For those of you looking to use next.js I would strongly recommend using our api directly instead of our SDK. We have extensive JS based examples in our official docs that show how to call our endpoints without needing the SDK.

**Comment by bigchiano** [comment]
> Right now we cannot promise any timelines on when nest.js will be supported by our JS SDK.
> 
> It’s on our roadmap, but is constantly being prioritized against our other platform needs.
> 
> For those of you looking to use next.js I would strongly recommend using our api directly instead of our SDK. We have extensive JS based examples in our official docs that show how to call our endpoints without needing the SDK.

Do I have permission to create a pull request for this?

**Comment by obo20** [comment]
@bigchiano Absolutely. I can't guarantee a timeline on merging it in (we'll have to evaluate it for safety first), but I can definitely say a working PR would expedite getting this working.
