### ISSUE TITLE
Example showing uploading to Pinata from form submission

### ISSUE THREAD

**Issue by hallahan** [PinataCloud/Pinata-SDK#47]
I'd like to have the ability to directly pipe files from a form upload to Pinata, avoiding needing a temporary file on the server. This is helpful for Lambda / serverless projects, as we'd like to avoid using the local filesystem.

Is there a straightforward way to do this?

I'm seeing `pinFileToIPFS` and `pinFromFS`, both of which assume there is a file on the local filesystem. Lastly, what is the advantage of using `pinFromFS` vs `pinFileToIPFS`?

**Comment by hypervillain** [comment]
`pinFileToIPFS` also accepts a ReadableStream, that can be created from buffers and strings. So, if you can send your file as one of these, you should be able to create a stream for it and send it using `pinFileToIPFS`.

**Comment by hypervillain** [comment]
```javascript
const { twitterScreenshot } = await screenshot(gatewayUrl)

const stream = Readable.from(twitterScreenshot)
stream.path = "twitter_screenshot.png"

const { IpfsHash: PreviewHash } = await pinata.pinFileToIPFS(stream)
````

This is a straight copy paste from my project: `twitterScreenshot` is a regular nodejs buffer. Don't forget to give your stream a `path` property

**Comment by Astro-Chimp** [comment]
This wouldn't work in a React app though, would it? Can't use nodejs there (notably, fs).

Looking for a way to convert a file thats input via a <input> html widget, into a readable stream in React....

Tried browserify-fs but it still complains it's not a readable stream when trying the API call to pinFileToIPFS

**Comment by stevedylandev** [comment]
For those still looking we have a quickstart of how to add Pinata to a React App: https://docs.pinata.cloud/quickstart/react
