### ISSUE TITLE
Method pinList throws error after multiple sequential calls

### ISSUE THREAD

**Issue by thesoulkiller** [PinataCloud/Pinata-SDK#51]
Hello,

I'm using pinata service(professional with 100GB bandwidth) as my database. I am pinning bunch of Json for each of my assets as: assetId: "t-0" , assetId: "t-1" etc. Then I'll get their cid's with 
``` 
try {
    res = await pinata.pinList({
      metadata: {
        keyvalues: {
          assetId: {
            value: `t-${asset_id}`,
            op: "eq",
          },
        },
      },
    });
} catch (error) {
    console.error("pinList error: ", error.toString());
    throw error;
  }
```
 as specified in docs. Then I use the retrieved cid to get json content from "js-ipfs" library to avoid making extra requests to pinata gateway. However, after 6-7 consequent successful requests pinata.pinList throws me this error:
```
pinList error:  Error: [object Object]
Error: [object Object]
    at <PATH>\node_modules\@pinata\sdk\lib\pinata-sdk.js:22176:16        
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I believe this behavior will block me from getting in live version. Any workaround ideas will be appreciated.

Thanks in advance.

**Comment by polluterofminds** [comment]
Hi @thesoulkiller, I'm taking a look at this now. Can you provide more info about how you are calling this function in your code? How often are you calling it and under what circumstances?

**Comment by thesoulkiller** [comment]
Hi @polluterofminds, I'm calling this function inside of koa's router get path. I've simplified my code as :
```
const getAssetCid = async (asset_id) => {
var res = null;
try {
    res = await pinata.pinList({
      metadata: {
        keyvalues: {
          assetId: {
            value: `t-${asset_id}`,
            op: "eq",
          },
        },
      },
    });
} catch (error) {
    console.error("pinList error: ", error.toString());
    throw error;
  }
  return res;
};

router.get("/:assetID", async (ctx, next) => {
  try {
    const asset_id = ctx.params.assetID;
    var asset_data = await getAssetCid(asset_id.toString());
    if (asset_data) {
      ctx.status = 200;
      ctx.body = {
        status: "success",
        cid: asset_data,
      };
    }
  }  catch (err) {
      console.log(err);
      ctx.status = 200;
      ctx.body = {
      status: "fail",
    };
  }
});
```
The scenario is, whenever user refreshes the page, the frontend sends get request to backend with asset id then gets cid.
Thank you for your response,

**Comment by polluterofminds** [comment]
@thesoulkiller this seems like a rate-limiting issue. I've replicated the error response you saw (it's actually inconsistent and I'm looking into that response now). But I'm surprised you're hitting rate-limiting with the approach you're taking. Do you have a significant volume of users hitting the page that makes these requests?

**Comment by thesoulkiller** [comment]
I'm the only user right now. Yeah, I'm surprised too :) Actually, I was a free user just today's morning, maybe the professional account has not been activated yet.

**Comment by polluterofminds** [comment]
@thesoulkiller That doesn't seem right. Can you check the network requests when you load the page that makes these requests? You'll want to look and see if the page is making requests even when the page is not refreshed. Is that possible to check? I know it's server-side code, but the front-end is triggering these server-side requests somehow. 

Also, the professional plan lifts rate limiting on the Gateway but not on the Pinata API. However, the good news is, you shouldn't see this happening under normal circumstances :)

**Comment by thesoulkiller** [comment]
>  lifts rate limiting on the Gateway but not on the Pinata API.
Oh no, I haven't tried gateway yet, but API support would be great :)

I'm using axios to make requests, I've looked network tab I'm doing get request once, moreover I've added console.log over backend side inside "router.get", still once. I don't know if it helps, I'm adding request/response headers below.
```
GET /0 HTTP/1.1
Host: 127.0.0.1:3001
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
Accept: application/json, text/plain, */*
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Origin: http://localhost:3000
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,tr;q=0.7
```
```
HTTP/1.1 200 OK
Vary: Origin
Access-Control-Allow-Origin: http://localhost:3000
Content-Type: application/json; charset=utf-8
Content-Length: 17
Date: Fri, 14 May 2021 14:21:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by polluterofminds** [comment]
@thesoulkiller would you be able to test out a request to the pinList endpoint without the Pinata SDK. You would do it like this: 

```js
export const userPinList = (pinataApiKey, pinataSecretApiKey, queryParams) => {
    let queryString = '?';
    if (queryParams.hashContains) {
        queryString = queryString + `hashContains=${queryParams.hashContains}&`;
    }
    if (queryParams.pinStartDate) {
        queryString = queryString + `pinStart=${queryParams.pinStartDate}&`;
    }
    if (queryParams.pinEndDate) {
        queryString = queryString + `pinEnd=${queryParams.pinEndDate}&`;
    }
    if (queryParams.unpinStartDate) {
        queryString = queryString + `unpinStart=${queryParams.unpinStartDate}&`;
    }
    if (queryParams.unpinEndDate) {
        queryString = queryString + `unpinEnd=${queryParams.unpinEndDate}&`;
    }
    if (queryParams.selectedPinStatus) {
        queryString = queryString + `pinFilter=${queryParams.selectedPinStatus}&`;
    }
    if (queryParams.unpinEndDate) {
        queryString = queryString + `unpinEnd=${queryParams.unpinEndDate}&`;
    }
    if (queryParams.unpinEndDate) {
        queryString = queryString + `unpinEnd=${queryParams.unpinEndDate}&`;
    }
    if (queryParams.pageLimit) {
        queryString = queryString + `pageLimit=${queryParams.pageLimit}&`;
    }
    if (queryParams.pageOffset) {
        queryString = queryString + `pageOffset=${queryParams.pageOffset}&`;
    }
    if (queryParams.nameContains) {
        queryString = queryString + `metadata[name]=${queryParams.nameContains}&`;
    }
    //Make sure keyvalues are properly formatted as described earlier in the docs.
    if (queryParams.keyvalues) {
        const stringKeyValues = JSON.stringify(queryParams.keyvalues);
        queryString = queryString + `metadata[keyvalues]=${stringKeyValues}`;
    }
    const url = `https://api.pinata.cloud/data/pinList${queryString}`;
    return axios
        .get(url, {
            headers: {
                pinata_api_key: pinataApiKey,
                pinata_secret_api_key: pinataSecretApiKey
            }
        })
        .then(function (response) {
            //handle response here
        })
        .catch(function (error) {
            //handle error here
        });
};
```

I know there's a little bit of conversion you have to do in order to get the query parameters passed through, so sorry about that! I mostly want you to try this so we can figure out what the actual error is. It might not be the rate-limiting problem.

**Comment by thesoulkiller** [comment]
Ok now, I'm now seeing error is based on rate-limiting. However with this method I'm getting this error harder than the previous one. What might be the difference ? There is 30 requests limiting in one minute I guess, maybe the other method's limit is lesser.
```
gateway error:  Error: Request failed with status code 429
    at createError (<PATH>\node_modules\axios\lib\core\createError.js:16:15)
    at settle (<PATH>\node_modules\axios\lib\core\settle.js:17:12)       
    at IncomingMessage.handleStreamEnd (<PATH>\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://api.pinata.cloud/data/pinList?metadata[keyvalues]={"assetId":{"value":"t-6","op":"eq"}}',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      pinata_api_key: '',
      pinata_secret_api_key: '',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },


.........


  response: {
    status: 429,
    statusText: 'Too Many Requests',
    headers: {
      server: 'nginx/1.16.1',
      date: 'Fri, 14 May 2021 16:09:13 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '135',
      connection: 'close',
      'x-powered-by': 'Express',
      vary: 'Origin',
      'access-control-allow-credentials': 'true',
      'x-ratelimit-limit': '30',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '1621008559',
      'retry-after': '60',
      etag: 'W/"87-3GatrlsluQTUcYCTnwI9Mw2C3w0"'
    },
    config: {
      url: 'https://api.pinata.cloud/data/pinList?metadata[keyvalues]={"assetId":{"value":"t-6","op":"eq"}}',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
```

**Comment by polluterofminds** [comment]
Thanks for trying that. I have a fix for the bad error response on the SDK that I'll be sending up soon. In the mean time, we need to figure out why you're getting rate-limited. To help keep the github repo clean, would you be ok if we move this to email or slack? 

The bug here, IMO, is the error response on the SDK. So I'll close this issue when that's released. But we do want to help you figure out the rate-limiting.

**Comment by thesoulkiller** [comment]
Yeah sure let's continue on mail.

**Comment by tverona1** [comment]
Hi @polluterofminds I'm also hitting this for pinList. Similar symptoms: I'm the only user and am not making frequent requests. I'd be curious if there are any updates on this. Thanks!

**Comment by polluterofminds** [comment]
Hi @tverona1, I'll re-open this issue just to be sure that there's not something strange going on in the SDK. Are you running the SDK in NodeJS or in the browser?

**Comment by tverona1** [comment]
Hi, yes this is via the sdk with Node

**Comment by WWWillems** [comment]
Also running into this issue using pinList, unpin and pinFileToIPFS. Trying to bulk add/delete using the NodeJS SDK.

**Comment by polluterofminds** [comment]
@tverona1 and @WWWillems can you let us know exactly how many requests per minute you are trying to make?

**Comment by SivaramPg** [comment]
@polluterofminds What is an acceptable number of requests per minute one can using the pinFileToIPFS method where it doesn't trigger the 429 error. I am trying to upload the large number of files of varying sizes. In general was hitting 100 rpm but in bursts of smaller files, was reaching 300 rpm which was triggerring the 429 errors.

**Comment by polluterofminds** [comment]
Hey @SivaramPg we actually just got this added to the documentation to help people out. Sorry it’s taken us so long to document the rate limiting: https://docs.pinata.cloud/rate-limits

**Comment by SivaramPg** [comment]
Thanks for the getting back so quickly @polluterofminds . Appreciate the updated docs.
