### ISSUE TITLE
HTTPError: Not Found when using ipfs-http-client

### ISSUE THREAD

**Issue by sparkplug0025** [PinataCloud/Pinata-SDK#52]
I believe the API is not respecting the new open api protocol somehow (or it is a bug in `ipfs-http-client`).

When I do a pin ls using the pinata endpoint, it works succesfully:
```ts
const result = await fetch("https://api.pinata.cloud/psa/pins", {
    headers: { Authorization: `Bearer ${ipfsConfig.pinataJwt}` },
});
const data = await result.json();
console.info(data)
```

When I try to use `ipfs-http-client` lib like this:
```ts
const IPFS_CLIENT = ipfsHttpClient({
    url: "https://api.pinata.cloud/psa",
    headers: { Authorization: `Bearer ${ipfsConfig.pinataJwt}` },
});

const x = await IPFS_CLIENT.pin.ls();
for await (const y of x) {
    console.info(y);
}
```

I receive this error:
```
HTTPError: Not Found
    at Object.errorHandler [as handleError] (~/myproject/node_modules/ipfs-http-client/src/lib/core.js:100:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.fetch (~/myproject/node_modules/ipfs-utils/src/http.js:146:9)
    at async Object.ls (~/myproject/node_modules/ipfs-http-client/src/pin/ls.js:43:17)
```

I tried with other methods too, like pin.add.

Does anyone know if I'm doing something wrong?

**Comment by polluterofminds** [comment]
Hey @sparkplug0025 the API definitely supports the pinning spec. It does look like the `ipfs-http-client` is supposed to support the pinning spec too now, so let me test this as well. If we can confirm it's a bug in that library, we'll point you to that repo to open a bug. But I definitely want to test first.

**Comment by obo20** [comment]
@sparkplug0025 the reason things are failing for you is because you're calling the ipfs.pin.ls function instead of the ipfs.pin.remote.ls function. 

The IPFS pinning service spec is only the "ipfs.pin.remote" functions, all other functions in the ipfs-http-client require a connection to a full IPFS node.

**Comment by sparkplug0025** [comment]
I was trying to play with the `pin.remote` but it looks like I need to have a full IPFS node and only then use the remote apis. I think I'm missing something or it seems a little bit off, since my whole point is to not spin up a local IPFS and pin the file through a remote pin service.

Does anyone have an example of using `ipfs-http-client` pinning to Pinata API without having a local node? Or it's just not possible due to the `ipfs-http-client` nature?

**Comment by obo20** [comment]
@sparkplug0025 unfortunately this isn't possible without running a local node due to the ipfs-http-client nature.
