### ISSUE TITLE
Help Wanted: Having issue to upload 10,000 file into IPFS directly. 

### ISSUE THREAD

**Issue by 0xisk** [PinataCloud/Pinata-SDK#55]
Hi, 

I'm trying to upload a lot of JSON files (10,000 JSON file) in IPFS using the following API from [py-ipfs-http-client package][1], and [go-ipfs v0.7][3] and when I try to open the hash with localhost IPFS domain it works `http://localhost:8081/ipfs/<hash>` but not with the main ipfs link `https://ipfs.io/ipfs/<hash>`, just keep loading forever. 

I tried again the same process the next day, but just a random small selection of the hashes started to work in `https://ipfs.io/ipfs/<hash>`, but the other do the same. 

Then I tried to use [Pinata][2] website to upload these JSON files but it kept loading without any successful message, and when I did a refresh it didn't work. 

I need your help to understand this behavior. And what may I do other than that to solve this challenge? 
Thanks.

  [1]: https://github.com/ipfs-shipyard/py-ipfs-http-client
  [2]: https://github.com/PinataCloud/Pinata-SDK
  [3]: https://github.com/ipfs/go-ipfs

**Comment by atharvashukla** [comment]
I had the same issue — the files kept loading. 

The files, however, loaded after waiting for a few minutes. 

Essentially, Pinata needs to traverse IPFS to look for the hash and pin it, which can take time. 

To make Pinata pin faster you can refer to the following subheading from the README:

https://github.com/PinataCloud/Pinata-SDK#host-node-multiaddresses
