### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by malkevych** [PinataCloud/Pinata-SDK#59]
Pls add support TypeScript.
I can't find any types when I run `npm i --save-dev @types/pinata__sdk`

It is crucial for community

**Comment by hubagaspar91** [comment]
@malkevych I have submitted a PR #58 which has just been merged that adds TS support to the project out of the box, without the need for an external types package. I reckon the npm package will soon be updated too, so keep an eye for that!

**Comment by obo20** [comment]
Added in: https://github.com/PinataCloud/Pinata-SDK/releases/tag/1.1.22
