### ISSUE TITLE
fs.createReadStream() for Firebase remote file in Node

### ISSUE THREAD

**Issue by cormacncheese** [PinataCloud/Pinata-SDK#63]
I am working with the pinFileToIPFS endpiont to upload a file toI PFSP however I can't seem to generate a readableStream of my remote file in firebase storage.

Ideally I would be able to do something like this:

const fs = require('fs');
const readableStreamForFile = fs.createReadStream(FIREBASE_STORAGE_DOWNLOAD_URL_HERE);

However my backend throws an error when I attempt to do so. What's the best way to createReadStream for files submitted through my frontend?

My remaining looks like this :

const options = {
      pinataMetadata: {
          name: 'MyCustomName',
          keyvalues: {
              customKey: 'customValue',
              customKey2: 'customValue2'
          }
      },
      pinataOptions: {
          cidVersion: 0
      }
  };
  await pinata.pinFileToIPFS(readableStreamForFile, options).then((result) => {
      console.log("RESULT: ", result);
  }).catch((err) => {
      console.log("ERR: ", err);
  });

**Comment by hubagaspar91** [comment]
@cormacncheese It seems to me that this thread on StackOverflow pretty much answers your question:

[https://stackoverflow.com/questions/65976322/how-to-create-a-readable-stream-from-a-remote-url-in-nodejs](https://stackoverflow.com/questions/65976322/how-to-create-a-readable-stream-from-a-remote-url-in-nodejs)

**Comment by cormacncheese** [comment]
Thank you.

I ended up getting it working using the following:

`const admin = require('firebase-admin')
const getRawBody = require('raw-body')
const {Storage} = require('@google-cloud/storage');


async function getStream (path) {
    const bucket = admin.storage().bucket()
    const file = await bucket.file(path)
    const buffer = await getRawBody(file.createReadStream()) 
}

await getStream()`
