### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by AnthonyJamez12** [PinataCloud/Pinata-SDK#64]
I don't know if this a like a true issue or even if I'm doing this correctly, still learning Github, but there is an issue with the email confirmation on y'alls website for signing up.

**Comment by obo20** [comment]
hey @AnthonyJamez12 could you send a support request to team@pinata.cloud? We'd be happy to take care of this for you!

**Comment by AnthonyJamez12** [comment]
@obo20 Hey sorry for not telling y'all I got the email confirmation. Thank you for reaching out and your service, I forgot to let yall know I got this fixed, still trying to get used to Github. Thank you again and you have a good one.
