### ISSUE TITLE
'PinSize' differs from pinned file size

### ISSUE THREAD

**Issue by jsonpoindexter** [PinataCloud/Pinata-SDK#66]
I am seeing that 'PinSize' returned from `pinList()` ( and `pinFileToIPFS()` results) do not match the actual size of the files that are pinned even though in the docs it defines: `PinSize: This is how large (in bytes) the content you just pinned is`

For example: 
File: https://gateway.pinata.cloud/ipfs/QmRgoqLEjPDzsgdY8Mx85KDhjhjr7U4WSdLTXz7res6oub 

`pinFileToIPFS()` results:
```
{
  IpfsHash: 'QmRgoqLEjPDzsgdY8Mx85KDhjhjr7U4WSdLTXz7res6oub',
  PinSize: 5568,
  Timestamp: '2021-06-23T02:04:34.529Z'
}
```

`pinList()` result:
```
  {
      id: '25a6c3e0-92ee-46c9-807d-cc339b570694',
      ipfs_pin_hash: 'QmRgoqLEjPDzsgdY8Mx85KDhjhjr7U4WSdLTXz7res6oub',
      size: 5568,
      user_id: 'ff5b457b-3a54-4174-bfc2-a420b2ba7856',
      date_pinned: '2021-06-23T02:04:34.529Z',
      date_unpinned: null,
      metadata: [Object],
      regions: [Array]
    }

```

File Properties:
![image](https://user-images.githubusercontent.com/5003899/123024024-4667f680-d38d-11eb-83d6-d4a9dd3baa57.png)

`Buffer.byteLength(fs.readFileSync('test-pin.png')))` results: `5557`

`pinFileToIPFS()` and `pinList()`  show a size of `5568` bytes while my OS and nodejs `Buffer.byteLength` shows `5557`
I am unsure why there is a difference. Can someone please help? Thank you!

**Comment by obo20** [comment]
@jsonpoindexter when IPFS creates objects in the data store, there's a little bit of metadata that's added to each bock of data, which is the reason for the small size discrepancy that you're seeing here. If you re-download the image from IPFS, you should see that the file size is what you're expecting. It's just when the data is inside of IPFS, it takes up a very very small amount of extra space as you've seen above.
