### ISSUE TITLE
Types: 

### ISSUE THREAD

**Issue by SuPuL** [PinataCloud/Pinata-SDK#76]
Hi, 
quick question to your TS types:

```
export type PinataPinOptions = {
    pinataMetadata?: Record<string, string | number | null> | undefined;
    pinataOptions?: PinataOptions | undefined;
};
```

seems to be wrong as `pinataMetadata`  is validated by `validateMetadata` which expects an `name?: string` and `keyvalues: Object`. So you cannot pass typesafe the `keyvalues` as `pinataMetadata` do not accept `objects` as values.

 Would you please correct me if I'm missing some type? 
 
 Thank you all for your work! 👋

**Comment by TrejGun** [comment]
same problem

**Comment by rommel-pinata** [comment]
Hello @SuPuL @TrejGun I found this PR that also address this issue. #116
