### ISSUE TITLE
pinFromFS: More than one file and/or directory was provided for pinning

### ISSUE THREAD

**Issue by jgrean81** [PinataCloud/Pinata-SDK#80]
You closed this as a previously raised issue but the problem persists.
Calling this function results in the report: "pinFromFS: More than one file and/or directory was provided for pinning."
Yes, it's a dir. Of course there is more than 1 file.
So what now?

**Comment by witwit** [comment]
No fix for this yet?
Absolute paths wor, but wrap the resulting URL in the same path.
`wrapWithDirectory: true` nor `wrapWithDirectory: false` work. The pinned dir always receives a full path. Horrible :-(

**Comment by mongodillo** [comment]
Did anyone manage to get this working?

I keep getting the same error message about More than one file and/or directory etc... it is annoying given PinfromFS is meant to handle a directory!

**Comment by witwit** [comment]
> Did anyone manage to get this working?
> 
> I keep getting the same error message about More than one file and/or directory etc... it is annoying given PinfromFS is meant to handle a directory!

Sort of...

First I do something like:
`process.chdir(path.resolve('YOUR PARENT/PROJECT DIR HERE'));`

and only then

`await pinata.pinFromFS("dist", {` 

to pin everything from the "dist" directory. Hope that helps!

**Comment by starryeyez024** [comment]
@jgrean81 did the suggested solution work for you? If so, please close out this ticket. Thanks!

**Comment by rommel-pinata** [comment]
This is now supported, and shouldn't be longer an issue. also added support windows and POSIX file structure.
