### ISSUE TITLE
PinataSDK pinnig a thumbnail Invalid request format

### ISSUE THREAD

**Issue by bennyvenassi** [PinataCloud/Pinata-SDK#81]
Hi,
i got a pretty similar problem to this issue: https://github.com/PinataCloud/Pinata-SDK/issues/9

The solution provided doesnt work for me. I try to create a thumbnail from a given URI and then save the resized image to pinata via the SDK.

Saving the thumbnail to my local fs works fine. While trying to pin it to pinata i got the an _Invalid request format_ Error.

My code so far:

```
            const fileRes = await axios.get(existingNFT.tokenURI, {
                responseType: 'arraybuffer'
            });
            const fetchedFile = Buffer.from(fileRes.data, 'binary');
                const options = { height: 300 }
                const thumbnail = await imageThumbnail(fetchedFile, options);
                const fileContents = Buffer.from(thumbnail, 'base64');
                const stream = Readable.from(fileContents);
                const pinataOptions = {
                    pinataMetadata: {
                        name: 'preview',
                        keyvalues: {
                            type: 'preview'
                        }
                    },
                    pinataOptions: {
                        cidVersion: 0
                    }
                };
                const previewRes = await pinata.pinFileToIPFS(stream, pinataOptions);
```

Thank you in advance!

**Comment by Oleh-Pashchenko** [comment]
The same thing

**Comment by bennyvenassi** [comment]
uploading the readable stream to a s3 bucket also works fine. :/

```
async function uploadReadableStream(stream, key) {
    const params = {Bucket: s3bucket, Key: key, Body: stream, ACL: 'public-read'};
    return s3.upload(params).promise();
  }
```

**Comment by polluterofminds** [comment]
@bennyvenassi I know that most people don't want to do this, but while our engineering team looks into this, a quick way to unblock yourself is to write the thumbnail to disk and then upload as normal using the pinFromFS method in the SDK.

**Comment by polluterofminds** [comment]
We have been unable to test this exact code because of an error with the image-thumbnail module. We get a module cannot be found error tied to it for the `sharp` module. We've been unable to find any resolution to that, but if you came across that error in your code and were able to solve it, please let us know!

**Comment by bennyvenassi** [comment]
Hi Justin,
thank you for your respond. I didnt face the sharp module error. Which version of image-thumbnail do you use? I'm using 1.0.14 in node.js with express. Regarding the package-lock image-thumbnail needs the following depencies:
```
        "image-thumbnail": {
            "version": "1.0.14",
            "resolved": "https://registry.npmjs.org/image-thumbnail/-/image-thumbnail-1.0.14.tgz",
            "integrity": "sha512-fXEGTGb5Rh8uKov74a4117/Bwm2NtEtHsSsw0mUBg7XxJLSLjmyYpCXWp2RlZ2eQnIUWVZmAVbDbij2CMDkx1g==",
            "requires": {
                "axios": "^0.21.1",
                "image-size": "^1.0.0",
                "sharp": "^0.28",
                "validator": "^13.0.0"
            }
```

I managed to get it work like you mentioned with a temp file to disk and then pinFromFS.

Here is my testcode:

```
exports.testThumbnail = async() => {
    console.log('testing thumbnail generator');
    try {
        const fileRes = await axios.get('https://xyz.mypinata.cloud/ipfs/xyz123, {
            responseType: 'arraybuffer'
        });
        const fetchedFile = Buffer.from(fileRes.data, 'binary');
        const fileType = fetchedFile.toString('hex', 0, 4);
        console.log(fileType);
        if (fileType !== '47494638') {
            console.log('creating thumnbail');
            const options = { height: 300,jpegOptions: {force: true} }
            const thumbnail = await imageThumbnail(fetchedFile, options);
            const fileContents = Buffer.from(thumbnail, 'base64');
            await uploadReadableStream(fileContents, 'test' + Date.now() + '.jpg');
        }
    } catch (error) {
        console.log(error);
    }
}

async function uploadReadableStream(stream, key) {
    fs.writeFile('./tmp/' + key, stream, async (err) =>{
        if (err) return console.error(err)
        console.log('file saved to ', key);
        const sourcePath = './tmp/' + key;
        const pinataOptions = {
            pinataMetadata: {
                name: key,
                keyvalues: {
                    contract: 'test',
                    token: 'test',
                    type: 'preview'
                }
            },
            pinataOptions: {
                cidVersion: 0
            }
        };
        try {
            const previewRes = await pinata.pinFromFS(sourcePath, pinataOptions);
            console.log(previewRes.IpfsHash);
            fs.unlinkSync(sourcePath);
        } catch (error) {
            console.log(error);
        }
    });
  }
```

**Comment by xtrinch** [comment]
I've been unable to pipe a stream of an image file gotten from S3 with `aws-sdk` to pinata because it returns `Invalid request format`.

**Comment by rommel-pinata** [comment]
hey @xtrinch Here is a working example

`const pinataSDK = require("../../lib/pinata-sdk");
const { GetObjectCommand, S3Client } = require("@aws-sdk/client-s3");

const pinata = new pinataSDK({
    pinataApiKey: "...",
    pinataSecretApiKey: "...",
});

const client = new S3Client({});

const main = async () => {
    const command = new GetObjectCommand({
        Bucket: "pinata-rommel-bucket",
        Key: "Screen Shot 2023-03-16 at 16.59.48.png",
    });

    try {
        const response = await client.send(command);
        const stream = await response.Body;

        const options = {
            pinataMetadata: {
                name: "Screen Shot 2023-03-16 at 16.59.48.png",
                keyvalues: {
                    customKey: "customValue",
                    customKey2: "customValue2",
                },
            },
            pinataOptions: {
                cidVersion: 0,
            },
        };
        const result = await pinata.pinFileToIPFS(
            stream,
            options
        );
        console.log(result);

        console.log(stream);
    } catch (err) {
        console.error(err);
    }
};

main();
`
