### ISSUE TITLE
Cant set JWT when using SDK

### ISSUE THREAD

**Issue by fsobh** [PinataCloud/Pinata-SDK#83]

**Comment by starryeyez024** [comment]
@fsobh  Can you please add more information to this ticket about what you are trying to accomplish? Otherwise please close it out if you solved this issue. Thank you.

**Comment by ohager** [comment]
It's possible to use the HTTP API with an Auth Token (JWT) (once authenticated), which is provided on Pinata Web. But this SDK does not seem to support it; only the way with API Key an API Secret.

https://docs.pinata.cloud/api-pinning/pinning-services-api#authentication

**Comment by rommel-pinata** [comment]
I created a PR that addressed this issue. Should be merged shortly!
