### ISSUE TITLE
Question: Can I pre-calculate the the CID returned by pinFileToIPFS?

### ISSUE THREAD

**Issue by hiddentao** [PinataCloud/Pinata-SDK#89]
I need to be able to pre-calculate the CID returned by `pinFileToIPFS` - is this possible?

**Comment by Theo-Farnole** [comment]
You can calculate the CID using the `ipfs-only-hash` package: https://www.npmjs.com/package/ipfs-only-hash.

Here's an example from the documentation of the package:
```js
const Hash = require('ipfs-only-hash')
const data = 'hello world!'
const hash = await Hash.of(data)
console.log(hash) // QmTp2hEo8eXRp6wg7jXv1BLCMh5a4F3B7buAUZNZUu772j
```

**Comment by rommel-pinata** [comment]
Hello @hiddentao and @Theo-Farnole, I don't think ipfs-only-hash would work since we use cid version 1. There's a simple way to accomplish you can see an example here https://www.npmjs.com/package/ipfs-core/v/0.10.6#getting-started. it has more options like cid version
