### ISSUE TITLE
How to use http api to upload files to the specified directory?

### ISSUE THREAD

**Issue by pyaming** [PinataCloud/Pinata-SDK#90]
How can I upload files to the specified directory? Does it have this function?

**Comment by noahliechti** [comment]
Yes it is documented here: [Pinata Documentation](https://docs.pinata.cloud/api-pinning/pin-file#pinning-a-directory-example)

If you use FormData you can use it like this:
```
let fd = new FormData();
  fd.append("file", fs.createReadStream(imagePath), {
    filepath: `directoryName/fileName`,
  });
```
