### ISSUE TITLE
Update or add file in a folder

### ISSUE THREAD

**Issue by stefanodecillis** [PinataCloud/Pinata-SDK#93]
Hi,

I chose Pinata to host multiple files for several users and I'm trying to collect them in folders. As per the title of this issue, I am trying to upload files into folders already pinned to IPFS. 
Digging into the SDK (I'm using nodejs) and rest API, I could not find a solution since I cannot pin files with an IPFS path ('CID/path/to/file').

I didn't try but I guess I would like to replicate this command: `ipfs add /PATH/TO/CONTENT/* -w `. 

Not sure it works in this way (the first time I'm working with IPFS) but I guess the process I want follows:

1.  upload a file inside a folder (using the CID)
2.  getting the new CID 
3.  saving the CID for references

What I am trying to avoid is to download the entire folder each time, unpin the latter and reupload it again with the new files. 

Many thanks to those whom can help me:)

**Comment by Theo-Farnole** [comment]
I'd also love to see this feature in the pinata API!

**Comment by albertoramires** [comment]
Would also appreciate this feature. 🙏

**Comment by rommel-pinata** [comment]
Hello @stefanodecillis,

There's a few issues with it. every folder of files generates a cid for the folder, every subfolder, and every file.  The cid is immutable. if you add a file to an existing folder and upload it again, the cid will change. This is core to the concept of IPFS, immutable data, and CIDs
