### ISSUE TITLE
Add functionality to nest json files with pinJSONToIPFS endpoint

### ISSUE THREAD

**Issue by noahliechti** [PinataCloud/Pinata-SDK#95]
Nesting files in folders is possible with the `pinFilesToIPFS` endpoint but not with `pinJSONToIPFS`.

This would be a helpful feature in my opinion.

**Comment by cs-balazs** [comment]
I don't know if you are aware, but it can be done with the `pinFilesToIPFS` endpoint.
```ts
const BASE_DIR = "some_base_directory_name"
const jsons = [ "{ ... }", "{ ... }" ]
const fileNames = [ "a.json", "b.json" ]
const formData = new FormData()

jsons.forEach((json, index) => {
  const blob = new Blob([json])
  formData.append("file", blob, `${BASE_DIR}/${fileNames[index]}`)
})

// Append pinataOptions, and pinataMetadata if needed, and send the request to pinFilesToIPFS
```
The `BASE_DIR` will not be created, the json files will be in the root of where the returned CID points to.

**Comment by noahliechti** [comment]
Yes, I managed to solve it using `pinFilesToIPFS`. But thanks for your response.
